<a href="https://colab.research.google.com/github/inyourT/DataAnalisDasar/blob/main/Array_indexing%2C_and_reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array = np.array([10,20,30,40,50])
slice_of_array = array[1:4]

print("Original Array:", array)
print("Sliced Array (Index 1 to 3):", slice_of_array)

Original Array: [10 20 30 40 50]
Sliced Array (Index 1 to 3): [20 30 40]


In [ ]:
array = np.array([1,2,3,4,5,6])
reshaped_array = array.reshape(2,3)

print("Original Array:")
print(array)
print("\nReshaped Array (2x3):")
print(reshaped_array)

Original Array:
[1 2 3 4 5 6]

Reshaped Array (2x3):
[[1 2 3]
 [4 5 6]]
