<a href="https://colab.research.google.com/github/inyourT/DataAnalisDasar/blob/main/Creating_Numpy_arrays_from_Pyhthon_List.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
python_list = [1,2,3,4,5]
numpy_array = np.array(python_list)
print("python list: ", python_list)
print("Numpy Array: ", numpy_array)

python list:  [1, 2, 3, 4, 5]
Numpy Array:  [1 2 3 4 5]


In [ ]:
nested_list = [[1,2,3], [4,5,6], [7,8,9]]
numppy_2d_array = np.array(nested_list)

print("Nested List:")
print(nested_list)
print("2D Numpy Array")
print(numppy_2d_array)

Nested List:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2D Numpy Array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
float_list = [1,2,3,4,5]
numpy_float_array = np.array(float_list, dtype=float)

print("Original List:", float_list)
print(numpy_float_array)

Original List: [1, 2, 3, 4, 5]
[1. 2. 3. 4. 5.]
