<a href="https://colab.research.google.com/github/inyourT/DataAnalisDasar/blob/main/Multidimensional_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
array_2d = np.array([[1,2,3], [4,5,6]])

array_3d = np.array([[1,2], [3,4], [5,6], [7,8]])

print(array_2d)
print(array_3d)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [9]:
array_2d = np.array([[10,20,30], [40,50,60], [70,80,90]])
array_3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]],[[9,10],[11,12]]])

# element_2d = array_2d[1,2]
# element_3d = array_3d[1,0,1]

slice_2d = array_2d[:, 1:3]
slice_3d = array_3d[1, :, :]

print(slice_2d)
print(slice_3d)

[[20 30]
 [50 60]
 [80 90]]
[[5 6]
 [7 8]]
